### ISSUE TITLE
Publish mainnet subgraph

### ISSUE THREAD

**Issue by RyRy79261** [mento-protocol/mento-subgraph#4]
**Description**

Publish and add signal to our mainnet subgaph([mento-celo](https://thegraph.com/studio/subgraph/mento-celo/)) for contracts on Celo mainnet following the steps below:

- Purchase enough GRT for at least 6 months of operation
- Fund the dev wallet with Arbitrum ETH & GRT. We only need enough ETH to send transactions and 10k GRT
- Using the dev wallet, publish the subgraph to Arbitrum on the subgraph studio. In this step also ensure the toggle to be the first to signal is set
- Take note of the production query URL and update the governance UI to make use of this

**References**
- [Publishing a Subgraph](https://thegraph.com/docs/en/publishing/publishing-a-subgraph/)

**Comment by chapati23** [comment]
@baroooo and I discussed it in grooming today but both were lacking some knowledge in The Graph to provide a confident estimate

**Comment by bayological** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Planning-65b8ace7a595330035ca810b/issues/mento-protocol/mento-subgraph/4?planning-poker) with Zenhub @nvtaveras @philbow61

**Comment by olenovyk** [comment]
I have topped up the dev wallet (0x56fD3F2bEE130e9867942D0F463a16fBE49B8d81) on Arbitrum with:
10,011 GRT and
0.015 ETH

**Comment by RyRy79261** [comment]
Celo graph published
https://thegraph.com/explorer/subgraphs/8C3iY7M5mPqYVFYENS6vFSsseZUtuWM5xTLiAqguGG4f?view=Query&chain=arbitrum-one
